name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Uppdatera till senaste versionen

      - name: Set up JDK
        uses: actions/setup-java@v2  # Uppdatera till senaste versionen
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
