name: Java Tests
on:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # or another distribution supporting Java 21

      - name: Build with Maven
        run: mvn -B clean test --file pom.xml